trailingComma: 'es5'
tabWidth: 4
semi: false
singleQuote: true
printWidth: 300
useTabs: false
bracketSpacing: true
arrowParens: 'avoid'
htmlWhitespaceSensitivity: 'ignore'

overrides:
  - files:
      - '*.yml'
      - '*.yaml'
    options:
      tabWidth: 4
